// enterprise-model-seed.ts — first-launch model configuration for the
// enterprise fork.
//
// CONTRACT (behavior-tested in enterprise-model-seed.test.ts):
//   1. Runs ONLY for the enterprise identity.
//   2. NEVER overwrites an existing config.yaml (an operator or the user may
//      have written one).
//   3. Writes NO secret. The seed source carries provider / base_url / model
//      only; the API key is supplied separately at install time (a `.env`
//      next to config.yaml, or `hermes auth`). Nothing key-shaped is ever
//      committed to the repo or baked into the installer.
//   4. Writes config.yaml with mode 0600.
//
// WHERE THE VALUES COME FROM (both live OUTSIDE the repo and the .app):
//   A. $HERMES_ENTERPRISE_MODEL_SEED  -> absolute path to a JSON file, or
//   B. <HERMES_HOME>/enterprise/model-seed.json
// If neither exists the seed is a deliberate no-op ('no-source'): the app
// still boots and the operator can drop the file and relaunch. THIS is the
// "framework in place, values pending" state — see ENTERPRISE.md.
//
// SEED JSON SHAPE:
//   {
//     "provider": "deepseek",                  // required
//     "model": "deepseek-chat",                // required
//     "base_url": "https://api.deepseek.com",  // optional
//     "api_key_env": "DEEPSEEK_API_KEY"        // optional, DOCUMENTATION only:
//                                              //   never written to config.yaml
//   }

import fs from 'node:fs'
import path from 'node:path'

export interface EnterpriseModelSeed {
  provider: string
  model: string
  base_url?: string
  api_key_env?: string
}

export type SeedReason = 'not-enterprise' | 'exists' | 'no-source' | 'invalid-source' | 'seeded'

export interface SeedResult {
  seeded: boolean
  reason: SeedReason
  configPath?: string
  source?: string
}

export type SeedSource =
  | { kind: 'ok'; seed: EnterpriseModelSeed; source: string }
  | { kind: 'invalid'; source: string }
  | { kind: 'none' }

/** The seed file candidates, in precedence order. A present-but-invalid file
 *  is reported as 'invalid' (not silently skipped) so a typo'd install-time
 *  drop is diagnosable. */
export function seedSourceCandidates(options: { hermesHome: string; env?: NodeJS.ProcessEnv }): string[] {
  const env = options.env ?? process.env
  const candidates: string[] = []
  const fromEnv = (env.HERMES_ENTERPRISE_MODEL_SEED || '').trim()
  if (fromEnv) {
    candidates.push(path.resolve(fromEnv))
  }
  candidates.push(path.join(options.hermesHome, 'enterprise', 'model-seed.json'))
  return candidates
}

function normalizeSeed(parsed: unknown): EnterpriseModelSeed | null {
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    return null
  }
  const record = parsed as Record<string, unknown>
  const provider = typeof record.provider === 'string' ? record.provider.trim() : ''
  const model = typeof record.model === 'string' ? record.model.trim() : ''
  if (!provider || !model) {
    return null
  }
  const seed: EnterpriseModelSeed = { provider, model }
  if (typeof record.base_url === 'string' && record.base_url.trim()) {
    seed.base_url = record.base_url.trim()
  }
  if (typeof record.api_key_env === 'string' && record.api_key_env.trim()) {
    seed.api_key_env = record.api_key_env.trim()
  }
  return seed
}

/** Resolve the seed source without writing anything. */
export function loadEnterpriseModelSeed(options: {
  hermesHome: string
  env?: NodeJS.ProcessEnv
  fsModule?: Pick<typeof fs, 'readFileSync'>
}): SeedSource {
  const fsModule = options.fsModule ?? fs
  for (const source of seedSourceCandidates(options)) {
    let raw: string
    try {
      raw = fsModule.readFileSync(source, 'utf8')
    } catch {
      continue
    }
    try {
      const seed = normalizeSeed(JSON.parse(raw))
      return seed ? { kind: 'ok', seed, source } : { kind: 'invalid', source }
    } catch {
      return { kind: 'invalid', source }
    }
  }
  return { kind: 'none' }
}

const yamlScalar = (value: string): string => JSON.stringify(value)

/** Render the minimal, secret-free model block. Values are always
 *  double-quoted so any YAML-hostile characters survive. */
export function renderSeedConfigYaml(seed: EnterpriseModelSeed): string {
  const lines = [
    '# Generated by Plankton on first launch (enterprise model seed).',
    '# This file is written only once and is safe to edit.',
    '# The API key is NOT stored here; see ENTERPRISE.md for where it comes from.',
    'model:',
    `  provider: ${yamlScalar(seed.provider)}`,
    `  default: ${yamlScalar(seed.model)}`
  ]
  if (seed.base_url) {
    lines.push(`  base_url: ${yamlScalar(seed.base_url)}`)
  }
  return `${lines.join('\n')}\n`
}

/**
 * Seed `<hermesHome>/config.yaml` on first launch. Idempotent and
 * non-destructive: an existing config.yaml is left byte-for-byte untouched.
 */
export function seedEnterpriseModelConfig(options: {
  identity: { enterprise?: boolean } | null | undefined
  hermesHome: string
  env?: NodeJS.ProcessEnv
  fsModule?: Pick<typeof fs, 'existsSync' | 'mkdirSync' | 'writeFileSync' | 'chmodSync' | 'readFileSync'>
}): SeedResult {
  if (!options.identity?.enterprise) {
    return { seeded: false, reason: 'not-enterprise' }
  }

  const fsModule = options.fsModule ?? fs
  const configPath = path.join(options.hermesHome, 'config.yaml')

  if (fsModule.existsSync(configPath)) {
    return { seeded: false, reason: 'exists', configPath }
  }

  const loaded = loadEnterpriseModelSeed(options)
  if (loaded.kind === 'none') {
    return { seeded: false, reason: 'no-source' }
  }
  if (loaded.kind === 'invalid') {
    return { seeded: false, reason: 'invalid-source', source: loaded.source }
  }

  fsModule.mkdirSync(path.dirname(configPath), { recursive: true })
  fsModule.writeFileSync(configPath, renderSeedConfigYaml(loaded.seed), { mode: 0o600 })
  // writeFileSync's mode is masked by the process umask; force 0600 so the
  // file that ends up next to a secret-bearing .env is never world-readable.
  try {
    fsModule.chmodSync(configPath, 0o600)
  } catch {
    void 0 // best effort; the write above still used 0600 as its base mode
  }

  return { seeded: true, reason: 'seeded', configPath, source: loaded.source }
}
